export interface EmailTemplate {
  id: string;
  name: string;
  description: string;
  subject: string;
  body: string;
  bannerColor: string;
}

export interface SentEmail {
  id: string;
  templateId: string;
  templateName: string;
  recipientEmail: string;
  recipientRole: string;
  recipientName: string;
  subject: string;
  body: string;
  date: string;
  referenceNumber: string;
}

export const DEFAULT_TEMPLATES: EmailTemplate[] = [
  {
    id: "cash_advance_submitted",
    name: "Cash Advance Request Submitted",
    description: "Dispatched to the Line Manager when a new funding memo is filed.",
    subject: "[SUBMITTED] New Cash Advance Request: {{referenceNumber}} - {{staffName}}",
    bannerColor: "#2563EB", // Blue
    body: `<div style="font-family: 'Inter', -apple-system, sans-serif; background-color: #F8FAFC; padding: 40px 20px; color: #1E293B; line-height: 1.5;">
  <div style="max-width: 605px; margin: 0 auto; bg: #FFFFFF; background-color: #FFFFFF; border-radius: 12px; overflow: hidden; border: 1px solid #E2E8F0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
    <!-- Header -->
    <div style="background-color: #2563EB; padding: 32px; text-align: center;">
      <h1 style="color: #FFFFFF; margin: 0; font-size: 22px; font-weight: 800; tracking-tight: -0.02em; text-transform: uppercase;">Funding Request Filed</h1>
      <p style="color: #DBEAFE; margin: 6px 0 0 0; font-size: 13px; font-family: monospace; letter-spacing: 0.1em;">MEMO & EXPENDITURE ASSIGNMENT SYSTEM</p>
    </div>
    
    <!-- Body -->
    <div style="padding: 32px;">
      <p style="margin: 0 0 20px 0; font-size: 14px; color: #475569;">Hello <strong>Tina Ofeno (Line Manager)</strong>,</p>
      
      <p style="margin: 0 0 20px 0; font-size: 14px; color: #475569; leading-relaxed: true;">
        A new administrative funding proposal has been logged and signed on the portal. Please review the parameters below and authorize forwarding into compliance desks:
      </p>
      
      <!-- Key Fields Info Block -->
      <div style="background-color: #F8FAFC; border: 1px solid #F1F5F9; border-radius: 8px; padding: 20px; margin-bottom: 24px;">
        <table style="width: 100%; font-size: 13px; cellspacing: 0; border-collapse: collapse;">
          <tr>
            <td style="padding: 6px 0; color: #64748B; font-weight: 500; width: 150px;">Reference Number:</td>
            <td style="padding: 6px 0; font-family: monospace; font-weight: 700; color: #1F2937;">{{referenceNumber}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748B; font-weight: 500;">Beneficiary Staff:</td>
            <td style="padding: 6px 0; font-weight: 700; color: #111827;">{{staffName}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748B; font-weight: 500;">Department:</td>
            <td style="padding: 6px 0; color: #374151;">{{department}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748B; font-weight: 500;">Requested Value:</td>
            <td style="padding: 6px 0; font-weight: 800; color: #2563EB; font-size: 15px;">\${{amountRequested}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748B; font-weight: 500;">Purpose of Fund:</td>
            <td style="padding: 6px 0; color: #374151; font-style: italic;">"{{purpose}}"</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748B; font-weight: 500;">Expected Retirement:</td>
            <td style="padding: 6px 0; color: #B45309; font-weight: 600;">{{expectedRetirementDate}}</td>
          </tr>
        </table>
      </div>
      
      <!-- Call to Action -->
      <div style="text-align: center; margin-bottom: 30px;">
        <a href="{{appUrl}}/requests" style="background-color: #2563EB; color: #FFFFFF; font-weight: 700; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-size: 13px; display: inline-block; box-shadow: 0 4px 6px -1px rgba(37, 99, 235, 0.2); transition: background-color 0.15s;">
          Review Requested Folder Now
        </a>
      </div>
      
      <p style="margin: 0; font-size: 11px; color: #94A3B8; text-align: center; border-top: 1px dotted #E2E8F0; padding-top: 20px;">
        This is an autogenerated system notification. To change notifications settings, access the system administrator control panel.
      </p>
    </div>
  </div>
</div>`
  },
  {
    id: "cash_advance_status_change",
    name: "Cash Advance Decision (Approve/Reject)",
    description: "Sent to the initiator (and preceding approvers) indicating that a decision has been taken.",
    subject: "[{{actionName}}] Workflow Update for Funding Memo {{referenceNumber}}",
    bannerColor: "#4F46E5", // Indigo
    body: `<div style="font-family: 'Inter', -apple-system, sans-serif; background-color: #F8FAFC; padding: 40px 20px; color: #1E293B; line-height: 1.5;">
  <div style="max-width: 605px; margin: 0 auto; background-color: #FFFFFF; border-radius: 12px; overflow: hidden; border: 1px solid #E2E8F0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
    <!-- Header -->
    <div style="background-color: #4F46E5; padding: 32px; text-align: center;">
      <h1 style="color: #FFFFFF; margin: 0; font-size: 22px; font-weight: 800; tracking-tight: -0.02em;">WORKFLOW PANEL DECISION</h1>
      <p style="color: #E0E7FF; margin: 6px 0 0 0; font-size: 13px; font-family: monospace; letter-spacing: 0.1em;">PORTAL TRANSACTION: {{referenceNumber}}</p>
    </div>
    
    <!-- Body -->
    <div style="padding: 32px;">
      <p style="margin: 0 0 16px 0; font-size: 14px; color: #475569;">Dear <strong>{{staffName}}</strong>,</p>
      
      <p style="margin: 0 0 20px 0; font-size: 14px; color: #475569; leading-relaxed: true;">
        Your administrative expenditure proposal has been scrutinized by <strong>{{actionUser}} ({{actionRole}})</strong>. The decision outcome has resolved as:
      </p>

      <!-- Status Callout -->
      <div style="text-align: center; margin-bottom: 24px; padding: 16px; border-radius: 8px; background-color: #EEF2F6; border-left: 5px solid #4F46E5;">
        <span style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 700; color: #4B5563; display: block; margin-bottom: 4px;">Current Workflow Decision</span>
        <strong style="font-size: 20px; color: #1E1B4B; text-transform: uppercase;">{{actionName}}</strong>
      </div>
      
      <!-- Comments Log -->
      <div style="background-color: #FFFDF5; border: 1px solid #FEF3C7; border-radius: 8px; padding: 20px; margin-bottom: 24px;">
        <span style="font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 700; color: #B45309; display: block; margin-bottom: 6px;">Evaluator Comments Logs</span>
        <p style="margin: 0; font-size: 13px; color: #514115; font-style: italic; font-weight: 500;">
          "{{comment}}"
        </p>
      </div>

      <!-- Quick Summary Table -->
      <div style="border-top: 1px solid #ECEFF2; padding-top: 16px; margin-bottom: 24px;">
        <table style="width: 100%; font-size: 12px;">
          <tr>
            <td style="color: #94A3B8; font-weight: 600; padding: 4px 0;">Requesting Agent:</td>
            <td style="color: #334155; font-weight: 700; padding: 4px 0;">{{staffName}}</td>
          </tr>
          <tr>
            <td style="color: #94A3B8; font-weight: 600; padding: 4px 0;">Funds Earmark:</td>
            <td style="color: #4F46E5; font-weight: 800; padding: 4px 0;">\${{amountRequested}}</td>
          </tr>
          <tr>
            <td style="color: #94A3B8; font-weight: 600; padding: 4px 0;">Purpose:</td>
            <td style="color: #334155; padding: 4px 0;">{{purpose}}</td>
          </tr>
          <tr>
            <td style="color: #94A3B8; font-weight: 600; padding: 4px 0;">Updated Portal Status:</td>
            <td style="color: #374151; font-weight: 700; padding: 4px 0;">{{status}}</td>
          </tr>
        </table>
      </div>
      
      <!-- CTA Button -->
      <div style="text-align: center; margin-bottom: 24px;">
        <a href="{{appUrl}}/requests" style="background-color: #4F46E5; color: #FFFFFF; font-weight: 700; text-decoration: none; padding: 10px 20px; border-radius: 6px; font-size: 13px; display: inline-block;">
          Go to Cash Advance Workspace
        </a>
      </div>
      
      <p style="margin: 0; font-size: 11px; color: #94A3B8; text-align: center; border-top: 1px dotted #E2E8F0; padding-top: 20px;">
        This email was dispatched securely. Compliance and Sarbanes-Oxley expenditure logs track active actions.
      </p>
    </div>
  </div>
</div>`
  },
  {
    id: "cash_advance_paid",
    name: "Payment Disbursed Confirmation",
    description: "Triggered instantly to the staff member when the Finance department dispatches funds.",
    subject: "[DISBURSED] Funding Proposal Settle Voucher: {{referenceNumber}} - PAID",
    bannerColor: "#059669", // Emerald Green
    body: `<div style="font-family: 'Inter', -apple-system, sans-serif; background-color: #F8FAFC; padding: 40px 20px; color: #1E293B; line-height: 1.5;">
  <div style="max-width: 605px; margin: 0 auto; background-color: #FFFFFF; border-radius: 12px; overflow: hidden; border: 1px solid #E2E8F0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
    <!-- Header -->
    <div style="background-color: #059669; padding: 32px; text-align: center;">
      <h1 style="color: #FFFFFF; margin: 0; font-size: 22px; font-weight: 800; tracking-tight: -0.02em;">FINANCIAL SETTLEMENT SUCCESS</h1>
      <p style="color: #DCFCE7; margin: 6px 0 0 0; font-size: 13px; font-family: monospace; letter-spacing: 0.1em;">ACCOUNTS TREASURY LEDGER</p>
    </div>
    
    <!-- Body -->
    <div style="padding: 32px;">
      <p style="margin: 0 0 20px 0; font-size: 14px; color: #475569;">Hello <strong>{{staffName}}</strong>,</p>
      
      <p style="margin: 0 0 20px 0; font-size: 14px; color: #475569; leading-relaxed: true;">
        We are pleased to notify you that the Finance Accounts Office has executed your approved Cash Advance funding request. The cash has been dispatched.
      </p>
      
      <!-- Transaction Receipt slip -->
      <div style="background-color: #ECFDF5; border: 1px solid #A7F3D0; border-radius: 10px; padding: 24px; margin-bottom: 24px;">
        <h4 style="margin: 0 0 16px 0; font-size: 12px; font-weight: 800; text-transform: uppercase; color: #047857; letter-spacing: 0.05em; border-bottom: 1px dashed #A7F3D0; padding-bottom: 10px;">Corporate Disbursements Voucher</h4>
        
        <table style="width: 100%; font-size: 13px;">
          <tr style="border-bottom: 1px solid #ECEFF2;">
            <td style="padding: 6px 0; color: #065F46; font-weight: 500;">Reference Code:</td>
            <td style="padding: 6px 0; font-weight: 700; color: #047857; font-family: monospace;">{{referenceNumber}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #065F46; font-weight: 500;">Disbursal Method:</td>
            <td style="padding: 6px 0; font-weight: 700; color: #1F2937;">{{paymentMethod}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #065F46; font-weight: 500;">Transaction Ref#:</td>
            <td style="padding: 6px 0; font-weight: 700; color: #1F2937; font-family: monospace;">{{paymentReference}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #065F46; font-weight: 500;">Amount Authorized:</td>
            <td style="padding: 6px 0; font-weight: 700; color: #1F2937;">\${{amountRequested}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #065F46; font-weight: 600; font-size: 14px;">Total Disbursed:</td>
            <td style="padding: 6px 0; font-weight: 900; color: #059669; font-size: 16px;">\${{amountPaid}}</td>
          </tr>
        </table>
      </div>

      <!-- Compliance Reminder -->
      <div style="background-color: #FFFBEB; border: 1px solid #FDE68A; border-radius: 8px; padding: 16px; margin-bottom: 24px; font-size: 12px; color: #78350F;">
        <strong>⚠️ Mandatory Retirement Compliance Window:</strong><br>
        Kindly file your detailed utilizing expense vouchers, matching invoices, and return any leftover excess balance by <strong>{{expectedRetirementDate}}</strong>. Failure to file by this date will restrict approval permissions on future funding proposals.
      </div>
      
      <!-- CTA Button -->
      <div style="text-align: center; margin-bottom: 24px;">
        <a href="{{appUrl}}/retirement" style="background-color: #059669; color: #FFFFFF; font-weight: 700; text-decoration: none; padding: 11px 22px; border-radius: 6px; font-size: 13px; display: inline-block;">
          Generate Retirement Claims Here
        </a>
      </div>
      
      <p style="margin: 0; font-size: 11px; color: #94A3B8; text-align: center; border-top: 1px dotted #E2E8F0; padding-top: 20px;">
        Authorized by Finch Robert, Lead Accounts Treasury desk. Records filed under SOX compliance index.
      </p>
    </div>
  </div>
</div>`
  },
  {
    id: "cash_advance_reminder",
    name: "Automated Overdue Reminders",
    description: "Triggered as warning/escalation when a pending transaction rests in the finance queue too long.",
    subject: "[WARNING REMINDER] Unresolved Funding Disbursement: {{referenceNumber}}",
    bannerColor: "#DC2626", // Deep Red
    body: `<div style="font-family: 'Inter', -apple-system, sans-serif; background-color: #FFF5F5; padding: 40px 20px; color: #1E293B; line-height: 1.5;">
  <div style="max-width: 605px; margin: 0 auto; background-color: #FFFFFF; border-radius: 12px; overflow: hidden; border: 1px solid #FCA5A5; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
    <!-- Header -->
    <div style="background-color: #DC2626; padding: 32px; text-align: center;">
      <h1 style="color: #FFFFFF; margin: 0; font-size: 20px; font-weight: 800; tracking-tight: -0.01em;">URGENT DISBURSEMENT WARNING</h1>
      <p style="color: #FEE2E2; margin: 6px 0 0 0; font-size: 13px; font-family: monospace; letter-spacing: 0.1em;">SYSTEM CRITICAL OVERDUE ALERTS</p>
    </div>
    
    <!-- Body -->
    <div style="padding: 32px;">
      <p style="margin: 0 0 16px 0; font-size: 14px; color: #475569;">Attention <strong>Finance Officer Desk & Approving Authorities</strong>,</p>
      
      <p style="margin: 0 0 20px 0; font-size: 14px; color: #DC2626; leading-relaxed: true; font-weight: 600;">
        SYSTEM ESCALATION POLICY: Request dossier: {{referenceNumber}} is flagged pending and unpaid after workflow authorization!
      </p>
      
      <!-- Key Fields Info Block -->
      <div style="background-color: #FDF2F2; border: 1px solid #FEE2E2; border-radius: 8px; padding: 20px; margin-bottom: 24px;">
        <table style="width: 100%; font-size: 12px; cellspacing: 0;">
          <tr>
            <td style="padding: 4px 0; color: #991B1B; font-weight: bold; width: 150px;">Pending Reference:</td>
            <td style="padding: 4px 0; font-family: monospace; font-weight: 700; color: #000;">{{referenceNumber}}</td>
          </tr>
          <tr>
            <td style="padding: 4px 0; color: #991B1B; font-weight: bold;">Filer Employee:</td>
            <td style="padding: 4px 0; font-weight: bold;">{{staffName}}</td>
          </tr>
          <tr>
            <td style="padding: 4px 0; color: #991B1B; font-weight: bold;">Earmarked Budget:</td>
            <td style="padding: 4px 0; font-weight: 850; color: #DC2626; font-size: 13px;">\s\${{amountRequested}}</td>
          </tr>
          <tr>
            <td style="padding: 4px 0; color: #991B1B; font-weight: bold;">Departmental Group:</td>
            <td style="padding: 4px 0;">{{department}}</td>
          </tr>
          <tr>
            <td style="padding: 4px 0; color: #991B1B; font-weight: bold;">Stated Purpose:</td>
            <td style="padding: 4px 0; font-weight: 500; font-style: italic;">"{{purpose}}"</td>
          </tr>
        </table>
      </div>

      <p style="margin: 0 0 24px 0; font-size: 13px; color: #475569; leading-relaxed: true;">
        To maintain administrative velocity and avoid delaying crucial operations repairs or travels, the Finance desk is required to disburse funds. Click the visual gateway below to execute transaction ledger settlements:
      </p>
      
      <!-- Call to Action -->
      <div style="text-align: center; margin-bottom: 24px;">
        <a href="{{appUrl}}/requests" style="background-color: #DC2626; color: #FFFFFF; font-weight: 800; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-size: 13px; display: inline-block;">
          Disburse Pending Funds Immediately
        </a>
      </div>
      
      <p style="margin: 0; font-size: 10px; color: #FCA5A5; text-align: center; border-top: 1px dotted #FCA5A5; padding-top: 20px; font-family: monospace;">
        ROUTING LOG: ADMIN_OFFICER -> HEAD_OF_ADMIN -> INTERNAL_CONTROL -> EXEC_OFFICE -> FINANCE_ALERT
      </p>
    </div>
  </div>
</div>`
  },
  {
    id: "retirement_submitted",
    name: "Retirement Claim Filed",
    description: "Fires instantly when an initiator submits a retirement claim for administrative auditing.",
    subject: "[RETIREMENT CLAIM] New Claim Folder RET-{{retirementId}} Submitted (Advance: {{referenceNumber}})",
    bannerColor: "#D97706", // Amber / Warm Orange
    body: `<div style="font-family: 'Inter', -apple-system, sans-serif; background-color: #F8FAFC; padding: 40px 20px; color: #1E293B; line-height: 1.5;">
  <div style="max-width: 605px; margin: 0 auto; background-color: #FFFFFF; border-radius: 12px; overflow: hidden; border: 1px solid #E2E8F0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
    <!-- Header -->
    <div style="background-color: #D97706; padding: 32px; text-align: center;">
      <h1 style="color: #FFFFFF; margin: 0; font-size: 22px; font-weight: 800; tracking-tight: -0.02em;">RETIREMENT CLAIM FILED</h1>
      <p style="color: #FEF3C7; margin: 6px 0 0 0; font-size: 13px; font-family: monospace; letter-spacing: 0.1em;">AUDITING REGISTER: RET-{{retirementId}}</p>
    </div>
    
    <!-- Body -->
    <div style="padding: 32px;">
      <p style="margin: 0 0 20px 0; font-size: 14px; color: #475569;">Hello <strong>Audit & Control Colleagues</strong>,</p>
      
      <p style="margin: 0 0 20px 0; font-size: 14px; color: #475569; leading-relaxed: true;">
        Corporate staff member <strong>{{staffName}}</strong> has compiled and dispatched a detailed fund utilization retirement folder matching outstanding advance reference <strong>{{referenceNumber}}</strong>.
      </p>
      
      <!-- Key Financial Totals -->
      <div style="background-color: #FFFBEB; border: 1px solid #FDE68A; border-radius: 8px; padding: 20px; margin-bottom: 24px;">
        <table style="width: 100%; font-size: 13px; cellspacing: 0; border-collapse: collapse;">
          <tr>
            <td style="padding: 6px 0; color: #92400E; font-weight: 600; width: 170px;">Retirement Folder Ref:</td>
            <td style="padding: 6px 0; font-family: monospace; font-weight: 700; color: #78350F;">RET-{{retirementId}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #92400E; font-weight: 600;">Original Disbursed Advance:</td>
            <td style="padding: 6px 0; font-weight: 700; color: #1F2937; font-family: monospace;">\${{amountAdvanced}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #92400E; font-weight: 600;">Utilized Receipts Sum:</td>
            <td style="padding: 6px 0; font-weight: 700; color: #1F2937; font-family: monospace;">\${{amountUtilized}}</td>
          </tr>
          <tr style="border-top: 1px dashed #FCD34D;">
            <td style="padding: 8px 0; color: #92400E; font-weight: bold; font-size: 14px;">Treasury Refund Due:</td>
            <td style="padding: 8px 0; font-weight: 900; color: #D97706; font-size: 16px; font-family: monospace;">\${{balanceReturned}}</td>
          </tr>
        </table>
      </div>

      <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; padding: 16px; border-radius: 8px; margin-bottom: 24px;">
        <span style="font-size: 10px; font-weight: bold; uppercase: true; letter-spacing: 0.05em; color: #64748B; display: block; margin-bottom: 4px;">Staff Explanation Narrative</span>
        <p style="margin: 0; font-size: 12px; color: #475569; font-style: italic;">
          "{{comment}}"
        </p>
      </div>
      
      <!-- CTA Button -->
      <div style="text-align: center; margin-bottom: 20px;">
        <a href="{{appUrl}}/retirement" style="background-color: #D97706; color: #FFFFFF; font-weight: 700; text-decoration: none; padding: 11px 22px; border-radius: 6px; font-size: 13px; display: inline-block; box-shadow: 0 4px 6px -1px rgba(217, 119, 6, 0.2);">
          Open Audit Board
        </a>
      </div>
      
      <p style="margin: 0; font-size: 11px; color: #94A3B8; text-align: center; border-top: 1px dotted #E2E8F0; padding-top: 20px;">
        Admin Memo Portal Scheduler Indexer. Barcodes verified. Immutable log recorded.
      </p>
    </div>
  </div>
</div>`
  }
];
